# model:
#______for cnn_encoder_______
input_size: [64,64,64]
dims : 3
model_name: ae
architecture: ae2
block_type:      # block_type can be  'double' 'triple' or empty(will use one conv each layer)
filters: [32,64,96]  # filters number can not be the same consecutively
kernel_size: [5,5,3]
in_planes: 1
out_planes: 1 
pad_mode: 'reflect'
act_mode: 'elu'
norm_mode: 'none'
#_______for mlp_encoder_____
mlp_filters: [96,48,24,12]
last_encoder: True 

#____for region_feature_extract___, is applied after cnn_encoder
avg_pool_size: [8,8,8] 
avg_pool_padding: False


# dataset:
e5: True 
dataset_name: 'knn_dataset'
batch_per_gpu: 256 
num_workers: 0
shuffle: true

#for mlp contrastive_learning
num_epochs: 10000
num_pairs: 16384 
start_epoch: 0
batch_size: 4096 
shuffle_very_epoch: 20 
valid_very_epoch: 50
save_very_epoch: 50
n_views: 4 
pos_weight_ratio: 2
# raw_img_resol:1um  feats_map_resol:16stride --> 16 um resol in feats_map
d_near: 8 
loss_enhance: True 
re_use: False 